version: '3'
services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    networks:
      - app-network
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge