version: '3'
services:
  app:
    build:
      args:
        - NODE_ENV=development
    command: ["yarn", "server:dev"]
    volumes:
      - ".:/home/node/app"
  nginx:
    volumes:
      - "./nginx:/etc/nginx"